import {
  Order,
  Partner,
  Product,
  LivreurProfile,
  CloseuseProfile,
  PayoutRequest,
  ActivityItem,
  Conversation,
  AgencyAlert,
  FinancialTransaction,
  CodCollection,
  CodRemittance,
  FinancialAuditLog,
  TreasuryManagerProfile,
  GlobalAuditLog,
  AuditSessionLog,
  PlatformNotification,
  PlatformUser,
  RoleDefinition,
  PermissionDefinition,
  PlatformSettings,
} from './types';

export const enoAgencies = [
  {
    id: 'cotonou',
    city: 'Cotonou',
    title: 'Agence Principale Littoral & Atlantique',
    coverage: 'Cotonou • Abomey-Calavi • Porto-Novo',
    primaryPhone: '+229 01 64 29 18 84',
    secondaryPhone: '+229 01 93 83 79 06',
    whatsapp: '2290164291884',
    address: 'Cadjehoun / Haie Vive, Cotonou, Bénin',
    status: 'Ouvert • 08h00 - 20h30',
    hubLead: 'Responsable Opérations Cotonou',
  },
  {
    id: 'lokossa',
    city: 'Lokossa',
    title: 'Agence Régionale Mono & Couffo',
    coverage: 'Lokossa • Mono • Couffo • Athiémé',
    primaryPhone: '+229 01 67 51 00 82',
    secondaryPhone: null,
    whatsapp: '2290167510082',
    address: 'Avenue Principale, Face Gare, Lokossa, Bénin',
    status: 'Ouvert • 08h00 - 19h00',
    hubLead: 'Responsable Antenne Lokossa',
  },
];

export const enoSocials = {
  tiktok: {
    handle: '@enolivraison',
    url: 'https://www.tiktok.com/@enolivraison',
    followers: '1 157+',
    likes: '4 351+',
    label: 'TikTok Officiel',
  },
  facebook: {
    name: 'Eno Livraison',
    url: 'https://www.facebook.com/enolivraison',
    label: 'Page Facebook',
  },
  instagram: {
    handle: '@enolivraison',
    url: 'https://www.instagram.com/enolivraison',
    label: 'Instagram',
  },
  whatsappCotonou: 'https://wa.me/2290164291884?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Cotonou',
  whatsappLokossa: 'https://wa.me/2290167510082?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Lokossa',
};

export const currentPartner: Partner = {
  id: 'p1',
  fullName: 'SINABEROGUI Jude',
  companyName: 'Afrimarket',
  email: 'judesinaberogui@gmail.com',
  phone: '+229 01 64 29 18 84',
  address: 'Cadjehoun, Cotonou, Bénin',
  city: 'Cotonou',
  isActive: true,
  isApproved: true,
  status: 'ACTIVE',
  category: 'Cosmétique & Beauté',
  websiteUrl: 'https://afrimarket.bj',
  deliveryFeeDefault: 2000,
  agencyCommissionDefault: 800,
  onboardingStep: 6,
  availableBalance: 4820000,
  pendingBalance: 1250000,
  ordersCountToday: 24,
  ordersCountMonth: 412,
  gmvProcessed: 18450000,
  confirmationRate: 88.5,
  deliverySuccessRate: 94.2,
  lastPayoutDate: '18 août 2026',
  lastActivityAt: 'Il y a 4 min',
  createdAt: '2026-01-15',
};

export const partners: Partner[] = [
  currentPartner,
  {
    id: 'p2',
    fullName: 'Epiphane Koumagnan',
    companyName: 'Bénin Shop',
    email: 'epiphane@beninshop.bj',
    phone: '+229 01 93 83 79 06',
    address: 'Zogbadjè, Abomey-Calavi',
    city: 'Abomey-Calavi',
    isActive: true,
    isApproved: true,
    status: 'ACTIVE',
    category: 'Électronique & High-Tech',
    websiteUrl: 'https://beninshop.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 6,
    availableBalance: 2450000,
    pendingBalance: 680000,
    ordersCountToday: 18,
    ordersCountMonth: 320,
    gmvProcessed: 12800000,
    confirmationRate: 84.0,
    deliverySuccessRate: 91.0,
    lastPayoutDate: '22 août 2026',
    lastActivityAt: 'Il y a 12 min',
    createdAt: '2026-02-10',
  },
  {
    id: 'p3',
    fullName: 'Fatou Dossou',
    companyName: 'Dossou Fashion (Côte d\'Ivoire)',
    email: 'fatou@dossoufashion.ci',
    phone: '+225 07 89 45 12 30',
    address: 'Abidjan / Hub Cotonou',
    city: 'Abidjan',
    isActive: true,
    isApproved: true,
    status: 'ACTIVE',
    category: 'Mode & Prêt-à-porter',
    websiteUrl: 'https://dossoufashion.com',
    deliveryFeeDefault: 2500,
    agencyCommissionDefault: 1000,
    onboardingStep: 6,
    availableBalance: 3600000,
    pendingBalance: 950000,
    ordersCountToday: 14,
    ordersCountMonth: 275,
    gmvProcessed: 14200000,
    confirmationRate: 86.2,
    deliverySuccessRate: 93.4,
    lastPayoutDate: '15 août 2026',
    lastActivityAt: 'Il y a 25 min',
    createdAt: '2026-03-05',
  },
  {
    id: 'p4',
    fullName: 'Arnaud Hounwanou',
    companyName: 'Lokossa Tech Store',
    email: 'arnaud@lokossatech.bj',
    phone: '+229 01 67 51 00 82',
    address: 'Centre-ville, Lokossa',
    city: 'Lokossa',
    isActive: true,
    isApproved: true,
    status: 'ACTIVE',
    category: 'Smartphones & Gadgets',
    websiteUrl: 'https://lokossatech.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 6,
    availableBalance: 1120000,
    pendingBalance: 310000,
    ordersCountToday: 8,
    ordersCountMonth: 140,
    gmvProcessed: 5600000,
    confirmationRate: 81.5,
    deliverySuccessRate: 89.0,
    lastPayoutDate: '28 août 2026',
    lastActivityAt: 'Il y a 1 heure',
    createdAt: '2026-03-12',
  },
  {
    id: 'p5',
    fullName: 'Karelle Hounsou',
    companyName: 'K-Beauty Cotonou',
    email: 'karelle@kbeauty.bj',
    phone: '+229 01 97 11 22 33',
    address: 'Fidjrossè Calvaire',
    city: 'Cotonou',
    isActive: true,
    isApproved: false,
    status: 'ONBOARDING',
    category: 'Skincare Coréen',
    websiteUrl: 'https://kbeauty.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 3,
    availableBalance: 0,
    pendingBalance: 0,
    ordersCountToday: 0,
    ordersCountMonth: 0,
    gmvProcessed: 0,
    confirmationRate: 0,
    deliverySuccessRate: 0,
    lastPayoutDate: 'Nouveau',
    lastActivityAt: 'Hier à 16:30',
    createdAt: '2026-08-30',
  },
  {
    id: 'p6',
    fullName: 'Gildas Tossou',
    companyName: 'Royal Shoes BJ',
    email: 'gildas@royalshoes.bj',
    phone: '+229 01 62 44 88 00',
    address: 'Haie Vive, Cotonou',
    city: 'Cotonou',
    isActive: true,
    isApproved: false,
    status: 'PENDING_VERIFICATION',
    category: 'Chaussures & Maroquinerie',
    websiteUrl: 'https://royalshoes.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 4,
    availableBalance: 450000,
    pendingBalance: 180000,
    ordersCountToday: 2,
    ordersCountMonth: 15,
    gmvProcessed: 850000,
    confirmationRate: 75.0,
    deliverySuccessRate: 80.0,
    lastPayoutDate: 'Aucun',
    lastActivityAt: 'Il y a 3 heures',
    createdAt: '2026-08-22',
  },
  {
    id: 'p7',
    fullName: 'Blandine Agbo',
    companyName: 'Afro Hair Care',
    email: 'blandine@afrohair.bj',
    phone: '+229 01 95 33 22 11',
    address: 'Akpakpa Dodomè',
    city: 'Cotonou',
    isActive: false,
    isApproved: true,
    status: 'SUSPENDED',
    suspensionReason: 'Taux de retour anormalement élevé (>40%) et contestation répétée des livraisons.',
    category: 'Soins Capillaires',
    websiteUrl: 'https://afrohair.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 6,
    availableBalance: 210000,
    pendingBalance: 0,
    ordersCountToday: 0,
    ordersCountMonth: 45,
    gmvProcessed: 1950000,
    confirmationRate: 62.0,
    deliverySuccessRate: 58.5,
    lastPayoutDate: '02 août 2026',
    lastActivityAt: 'Suspendu le 24 août',
    createdAt: '2026-04-10',
  },
];

export const livreurs: LivreurProfile[] = [
  {
    id: 'liv-1',
    name: 'Rachad ADECHINA',
    email: 'rachad.adechina@enolivraison.com',
    phone: '+229 01 97 45 12 00',
    zone: 'Cotonou Centre',
    secondaryZones: ['Akpakpa', 'Fidjrossè', 'Cadjehoun'],
    vehicle: 'Moto Yamaha YB-125',
    licensePlate: 'RB-4589-AF',
    isActive: true,
    availabilityStatus: 'IN_TRANSIT',
    mustChangePassword: false,
    assignedOrdersCount: 4,
    maxActiveCapacity: 8,
    deliveredTodayCount: 6,
    deliveredWeekCount: 38,
    deliveredMonthCount: 164,
    failedTodayCount: 0,
    cashCollectedToday: 78600,
    commissionPerDelivery: 1500,
    successRate: 97.4,
    avgDeliveryTimeMinutes: 34,
    lastActivityAt: 'Il y a 6 min',
  },
  {
    id: 'liv-2',
    name: 'Wilfried HOUNGBEDJI',
    email: 'wilfried.houngbedji@enolivraison.com',
    phone: '+229 01 66 32 98 11',
    zone: 'Abomey-Calavi',
    secondaryZones: ['Godomey', 'Arconville', 'Zogbadjè'],
    vehicle: 'Moto TVS HLX 150',
    licensePlate: 'RB-9102-BD',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    assignedOrdersCount: 2,
    maxActiveCapacity: 8,
    deliveredTodayCount: 5,
    deliveredWeekCount: 32,
    deliveredMonthCount: 142,
    failedTodayCount: 1,
    cashCollectedToday: 55200,
    commissionPerDelivery: 1500,
    successRate: 94.1,
    avgDeliveryTimeMinutes: 41,
    lastActivityAt: 'Il y a 12 min',
  },
  {
    id: 'liv-3',
    name: 'Rodrigue KOUTON',
    email: 'rodrigue.kouton@enolivraison.com',
    phone: '+229 01 95 14 78 22',
    zone: 'Porto-Novo',
    secondaryZones: ['Ouando', 'Sèmè-Kpodji', 'Djassin'],
    vehicle: 'Moto Bajaj Boxer 100',
    licensePlate: 'RB-2241-CC',
    isActive: true,
    availabilityStatus: 'PAUSED',
    mustChangePassword: false,
    assignedOrdersCount: 1,
    maxActiveCapacity: 8,
    deliveredTodayCount: 4,
    deliveredWeekCount: 26,
    deliveredMonthCount: 118,
    failedTodayCount: 0,
    cashCollectedToday: 42800,
    commissionPerDelivery: 1500,
    successRate: 96.0,
    avgDeliveryTimeMinutes: 38,
    lastActivityAt: 'Il y a 25 min',
  },
  {
    id: 'liv-4',
    name: 'Kevin ASSOGBA',
    email: 'kevin.assogba@enolivraison.com',
    phone: '+229 01 96 78 12 44',
    zone: 'Cotonou Nord',
    secondaryZones: ['Agla', 'Vedoko', 'Menontin'],
    vehicle: 'Moto Haojue 110',
    licensePlate: 'RB-7841-DD',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    assignedOrdersCount: 0,
    maxActiveCapacity: 8,
    deliveredTodayCount: 3,
    deliveredWeekCount: 29,
    deliveredMonthCount: 125,
    failedTodayCount: 0,
    cashCollectedToday: 36000,
    commissionPerDelivery: 1500,
    successRate: 98.2,
    avgDeliveryTimeMinutes: 29,
    lastActivityAt: 'Il y a 3 min',
  },
  {
    id: 'liv-5',
    name: 'David KOUASSI',
    email: 'david.kouassi@enolivraison.com',
    phone: '+229 01 67 44 99 01',
    zone: 'Abomey-Calavi',
    secondaryZones: ['Tankpe', 'Bidossessi'],
    vehicle: 'Moto Yamaha YB-125',
    licensePlate: 'RB-3301-EE',
    isActive: true,
    availabilityStatus: 'IN_TRANSIT',
    mustChangePassword: false,
    assignedOrdersCount: 3,
    maxActiveCapacity: 8,
    deliveredTodayCount: 4,
    deliveredWeekCount: 28,
    deliveredMonthCount: 110,
    failedTodayCount: 0,
    cashCollectedToday: 49500,
    commissionPerDelivery: 1500,
    successRate: 95.0,
    avgDeliveryTimeMinutes: 37,
    lastActivityAt: 'Il y a 8 min',
  },
  {
    id: 'liv-6',
    name: 'Moussa KANHOUN',
    email: 'moussa.kanhoun@gmail.com',
    phone: '+229 01 97 88 44 22',
    zone: 'Cotonou Littoral',
    secondaryZones: ['Cadjehoun', 'Haie Vive'],
    vehicle: 'Moto TVS 150',
    licensePlate: 'RB-1190-FF',
    isActive: true,
    availabilityStatus: 'OFFLINE',
    mustChangePassword: true,
    temporaryCode: '849201',
    assignedOrdersCount: 0,
    maxActiveCapacity: 8,
    deliveredTodayCount: 0,
    deliveredWeekCount: 12,
    deliveredMonthCount: 48,
    failedTodayCount: 0,
    cashCollectedToday: 0,
    commissionPerDelivery: 1500,
    successRate: 91.5,
    avgDeliveryTimeMinutes: 45,
    lastActivityAt: 'Hier à 19:30',
  },
];

export const closeuses: CloseuseProfile[] = [
  {
    id: 'cls-1',
    name: 'Sarah ADANHO',
    email: 'sarah.adanho@enolivraison.com',
    phone: '+229 01 64 29 18 84',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    callsTodayCount: 42,
    confirmedTodayCount: 34,
    confirmedWeekCount: 198,
    confirmedMonthCount: 840,
    cancelledTodayCount: 3,
    unreachableTodayCount: 5,
    callbacksScheduledToday: 4,
    conversionRate: 82.5,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 4,
    activeConversationsCount: 2,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 4.2,
    languages: ['Français', 'Fon', 'Yoruba'],
    zones: ['Cotonou', 'Calavi'],
    skills: ['High-Ticket', 'Cosmétique', 'B2B'],
    lastActivityAt: 'Il y a 2 min',
  },
  {
    id: 'cls-2',
    name: 'Marie KOUASSI',
    email: 'marie.kouassi@enolivraison.com',
    phone: '+229 01 93 83 79 06',
    isActive: true,
    availabilityStatus: 'BUSY',
    mustChangePassword: false,
    callsTodayCount: 38,
    confirmedTodayCount: 29,
    confirmedWeekCount: 176,
    confirmedMonthCount: 790,
    cancelledTodayCount: 4,
    unreachableTodayCount: 5,
    callbacksScheduledToday: 6,
    conversionRate: 78.4,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 11,
    activeConversationsCount: 4,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 5.1,
    languages: ['Français', 'Fon'],
    zones: ['Cotonou Littoral', 'Porto-Novo'],
    skills: ['Mode & Textile', 'Électronique'],
    lastActivityAt: 'Il y a 5 min',
  },
  {
    id: 'cls-3',
    name: 'Carine DOSSOU',
    email: 'carine.dossou@enolivraison.com',
    phone: '+229 01 61 77 99 33',
    isActive: true,
    availabilityStatus: 'PAUSED',
    mustChangePassword: false,
    callsTodayCount: 28,
    confirmedTodayCount: 22,
    confirmedWeekCount: 145,
    confirmedMonthCount: 650,
    cancelledTodayCount: 2,
    unreachableTodayCount: 4,
    callbacksScheduledToday: 3,
    conversionRate: 81.0,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 6,
    activeConversationsCount: 1,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 4.8,
    languages: ['Français', 'Goun', 'Yoruba'],
    zones: ['Porto-Novo', 'Sèmè-Kpodji'],
    skills: ['Gadgets Tech', 'Maison'],
    lastActivityAt: 'Il y a 18 min',
  },
  {
    id: 'cls-4',
    name: 'Inès TOVIHOUDJI',
    email: 'ines.tovihoudji@enolivraison.com',
    phone: '+229 01 97 55 22 11',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    callsTodayCount: 31,
    confirmedTodayCount: 26,
    confirmedWeekCount: 160,
    confirmedMonthCount: 710,
    cancelledTodayCount: 2,
    unreachableTodayCount: 3,
    callbacksScheduledToday: 2,
    conversionRate: 83.8,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 3,
    activeConversationsCount: 1,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 3.9,
    languages: ['Français', 'Fon', 'Anglais'],
    zones: ['Cotonou Centre'],
    skills: ['Vente Express', 'Relations VIP'],
    lastActivityAt: 'Il y a 8 min',
  },
  {
    id: 'cls-5',
    name: 'Flora AGBANGLA',
    email: 'flora.agbangla@gmail.com',
    phone: '+229 01 66 11 88 44',
    isActive: true,
    availabilityStatus: 'OFFLINE',
    mustChangePassword: true,
    temporaryCode: '315792',
    callsTodayCount: 0,
    confirmedTodayCount: 0,
    confirmedWeekCount: 45,
    confirmedMonthCount: 190,
    cancelledTodayCount: 0,
    unreachableTodayCount: 0,
    callbacksScheduledToday: 0,
    conversionRate: 75.0,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 0,
    activeConversationsCount: 0,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 5.5,
    languages: ['Français', 'Fon'],
    zones: ['Abomey-Calavi'],
    skills: ['Généraliste'],
    lastActivityAt: 'Hier à 18:40',
  },
];

export const initialPayoutRequests: PayoutRequest[] = [
  {
    id: 'wd-2048',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    amount: 500000,
    reservedAmount: 500000,
    operator: 'LEEKPAY',
    leekpayPhone: '+229 01 97 36 29 06',
    leekpayCountry: 'Bénin (BJ)',
    phone: '01 97 36 29 06',
    countryCode: '+229',
    requestedAt: '2026-09-04T09:30:00',
    status: 'PENDING',
    balanceBefore: 4820000,
    balanceAfter: 4320000,
    internalNote: 'Vérification bancaire effectuée. Prêt pour validation.',
  },
  {
    id: 'wd-2047',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion',
    amount: 360000,
    reservedAmount: 360000,
    operator: 'USDT',
    cryptoAddress: 'TM1R9pQcKsXkQpXg8y6Jc5kZ3v4mN7bQ8L',
    cryptoNetwork: 'TRC-20 (Tron Network)',
    cryptoEstimatedUsdt: 600,
    requestedAt: '2026-09-04T08:15:00',
    status: 'IN_VERIFICATION',
    balanceBefore: 1250000,
    balanceAfter: 890000,
    internalNote: 'Contrôle adresse de wallet USDT TRC-20 en cours.',
  },
  {
    id: 'wd-2046',
    partnerId: 'p4',
    partnerName: 'Lokossa Tech Store',
    amount: 220000,
    reservedAmount: 220000,
    operator: 'BINANCE_PAY',
    binancePayId: '849201938',
    binanceEmail: 'lokossatech@gmail.com',
    requestedAt: '2026-09-03T16:45:00',
    status: 'APPROVED',
    approvedAt: '2026-09-03T17:10:00',
    adminProcessorName: 'Direction ENO (Super Admin)',
    balanceBefore: 940000,
    balanceAfter: 720000,
    internalNote: 'PayId validé via API Binance Merchant.',
  },
  {
    id: 'wd-2045',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    amount: 120000,
    operator: 'LEEKPAY',
    leekpayPhone: '+229 01 93 83 79 06',
    phone: '01 93 83 79 06',
    countryCode: '+229',
    requestedAt: '2026-09-02T16:15:00',
    status: 'PAID',
    approvedAt: '2026-09-02T16:35:00',
    paidAt: '2026-09-02T16:40:00',
    adminProcessorName: 'Direction ENO (Super Admin)',
    paymentReference: 'LK-PAY-984214-BJ',
    txReference: 'TX-ENO-984214',
    balanceBefore: 1200000,
    balanceAfter: 1080000,
    internalNote: 'Virement LeekPay exécuté avec succès.',
  },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'ROULEAU DE COLORIAGE ET DESSIN MAGIQUE',
    price: 7800,
    initialStock: 150,
    remainingStock: 82,
    deliveredCount: 68,
    partnerId: 'p1',
    createdAt: '2026-01-20',
  },
  {
    id: 'prod2',
    name: 'MINI VENTILATEUR PORTATIF RECHARGEABLE USB',
    price: 9500,
    initialStock: 80,
    remainingStock: 34,
    deliveredCount: 46,
    partnerId: 'p1',
    createdAt: '2026-02-01',
  },
  {
    id: 'prod3',
    name: 'CORRECTEUR DE POSTURE DOS & ÉPAULES AJUSTABLE',
    price: 11000,
    initialStock: 60,
    remainingStock: 18,
    deliveredCount: 42,
    partnerId: 'p1',
    createdAt: '2026-02-15',
  },
  {
    id: 'prod4',
    name: 'MONTRE CONNECTÉE FITNESS PRO WATERPROOF',
    price: 18500,
    initialStock: 45,
    remainingStock: 12,
    deliveredCount: 33,
    partnerId: 'p2',
    createdAt: '2026-02-20',
  },
  {
    id: 'prod5',
    name: 'SERUM ANTI-TACHES ÉCLAT VISAGE 50ML',
    price: 14000,
    initialStock: 100,
    remainingStock: 48,
    deliveredCount: 52,
    partnerId: 'p3',
    createdAt: '2026-03-01',
  },
];

export const orders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'CMD-BJ9K2L1A',
    clientName: 'SOULEYMANE DIOP',
    clientPhone: '+229 01 97 36 29 06',
    region: 'Littoral',
    address: 'AKPAKPA, Face Stade René Pleven',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE (x2)',
    quantity: 2,
    totalPrice: 15600,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Client confirmé par Inès. Livreur Rachad en route (créneau 14h-16h).',
    createdAt: '2026-09-03T09:15:00',
    updatedAt: '2026-09-03T11:00:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Client très réactif, prêt avec le montant exact.',
    callCount: 1,
    deliveryTimeSlot: '14h00 - 16h00',
  },
  {
    id: 'o2',
    orderNumber: 'CMD-BJH7X8P9',
    clientName: 'NADÈGE HOUNNOU',
    clientPhone: '+229 01 66 12 45 89',
    region: 'Atlantique',
    address: 'GODOMEY, Carrefour Togoudo',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 1,
    totalPrice: 9500,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_ATTENTE',
    comment: 'Nouvelle commande boutique. À appeler en priorité.',
    createdAt: '2026-09-03T11:45:00',
    updatedAt: '2026-09-03T11:45:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    callCount: 0,
  },
  {
    id: 'o3',
    orderNumber: 'CMD-BJ3M4N5K',
    clientName: 'BRICE GBAGUIDI',
    clientPhone: '+229 01 95 88 77 44',
    region: 'Littoral',
    address: 'CADJEHOUN, Derrière Église St Michel',
    city: 'Cotonou',
    products: 'CORRECTEUR DE POSTURE',
    quantity: 1,
    totalPrice: 11000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'CONFIRMEE',
    comment: 'Validé par Chimène. Prêt pour dispatch.',
    createdAt: '2026-09-03T08:30:00',
    updatedAt: '2026-09-03T10:15:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Livraison bureau souhaitée avant 17h.',
    callCount: 1,
    deliveryTimeSlot: '15h30',
  },
  {
    id: 'o4',
    orderNumber: 'CMD-BJ2F4X7Y',
    clientName: 'MARIE-CLAIRE TOSSOU',
    clientPhone: '+229 01 67 89 23 45',
    region: 'Littoral',
    address: 'HAIE VIVE, Rue 12.045',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE',
    quantity: 1,
    totalPrice: 7800,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'LIVREE',
    comment: 'Colis remis en main propre. Cash 7 800 F encaissé.',
    createdAt: '2026-09-02T14:00:00',
    updatedAt: '2026-09-02T16:30:00',
    deliveredAt: '2026-09-02T16:30:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    codCollected: true,
  },
  {
    id: 'o5',
    orderNumber: 'CMD-BJ8R9T2W',
    clientName: 'JEAN-BAPTISTE DANSOU',
    clientPhone: '+229 01 96 44 33 22',
    region: 'Atlantique',
    address: 'TANKPÈ, Carrefour IITA',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 2,
    totalPrice: 19000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'A_RAPPELER',
    comment: 'Injoignable 1er appel (occupé). Rappel programmé à 17h00.',
    createdAt: '2026-09-03T10:00:00',
    updatedAt: '2026-09-03T11:20:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    closingNotes: 'Téléphone sonne mais ne décroche pas.',
    callCount: 1,
  },
  {
    id: 'o6',
    orderNumber: 'CMD-BJ5K9L2M',
    clientName: 'AÏCHA CISSE',
    clientPhone: '+229 01 68 00 11 22',
    region: 'Ouémé',
    address: 'OUANDO, Marché Ouando',
    city: 'Porto-Novo',
    products: 'SÉRUM ANTI-TACHES ÉCLAT',
    quantity: 1,
    totalPrice: 14000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Confirmé. Livreur Rodrigue en route.',
    createdAt: '2026-09-03T09:40:00',
    updatedAt: '2026-09-03T11:10:00',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion (CI)',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-3',
    assignedLivreurName: 'Rodrigue K.',
    deliveryTimeSlot: '15h00',
  },
];

export function getPartnerById(partnerId: string): Partner | undefined {
  return partners.find((p) => p.id === partnerId);
}

export function getPartnerOrders(partnerId: string): Order[] {
  return orders.filter((o) => o.partnerId === partnerId);
}

export function getPartnerProducts(partnerId: string): Product[] {
  return products.filter((p) => p.partnerId === partnerId);
}

export function formatCFA(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' FCFA';
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' FCFA';
}

export function generateOrderNumber(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'CMD-BJ';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// 🟢 Activité temps réel de l'agence (Agency Pulse)
export const initialAgencyPulseActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'ORDER_DELIVERED',
    title: 'Livraison réussie & COD encaissé',
    description: 'Rodrigue K. a remis le colis CMD-BJ5K9L2M (14 000 F) à Ouando.',
    time: 'Il y a 3 min',
    orderNumber: 'CMD-BJ5K9L2M',
    partnerName: 'Dossou Fashion',
    amount: 14000,
  },
  {
    id: 'act-2',
    type: 'ORDER_CONFIRMED',
    title: 'Commande confirmée par Closing',
    description: 'Inès T. a validé la commande CMD-BJ7X8Y9Z après 1 appel (15 min).',
    time: 'Il y a 11 min',
    orderNumber: 'CMD-BJ7X8Y9Z',
    partnerName: 'Afrimarket',
    amount: 23400,
  },
  {
    id: 'act-3',
    type: 'ORDER_DISPATCHED',
    title: 'Colis assigné au livreur de zone',
    description: 'CMD-BJ3C4D5E assignée à Gaston B. (Zone Akpakpa & PK10).',
    time: 'Il y a 18 min',
    orderNumber: 'CMD-BJ3C4D5E',
    partnerName: 'Bénin Shop',
    amount: 15600,
  },
  {
    id: 'act-4',
    type: 'PAYOUT_REQUESTED',
    title: 'Nouvelle demande de retrait soumise',
    description: 'Dossou Fashion demande 360 000 F CFA en USDT TRC-20.',
    time: 'Il y a 32 min',
    partnerName: 'Dossou Fashion',
    amount: 360000,
  },
  {
    id: 'act-5',
    type: 'MESSAGE_RECEIVED',
    title: 'Message urgent reçu au Support',
    description: 'Afrimarket : "Pouvez-vous prioriser la livraison à Haie Vive ?"',
    time: 'Il y a 45 min',
    partnerName: 'Afrimarket',
  },
];

// 💬 Conversations du Hub de Communication
export const initialConversations: Conversation[] = [
  {
    id: 'conv-1',
    partnerId: 'p1',
    partnerName: 'Jude Sina',
    companyName: 'Afrimarket',
    phone: '+229 01 97 36 29 06',
    lastMessage: 'Bonjour ! Quel est le délai pour le virement MTN Money demandé ce matin ?',
    lastMessageAt: 'Il y a 3 min',
    unreadCount: 2,
    status: 'URGENT',
    priority: 'URGENT',
    assignedAgentId: 'cls-1',
    assignedAgentName: 'Sarah A.',
    assignedAgentRole: 'Closeuse Senior',
    relatedOrderNumber: 'CMD-1048',
    firstResponseTimeMinutes: 4,
    avgResponseTimeMinutes: 7,
    slaStatus: 'WARNING_SLA',
    assignmentHistory: [
      {
        id: 'ah-1',
        assignedToName: 'Sarah A.',
        assignedToRole: 'Closeuse',
        timestamp: '04 sept. — 10:32',
        reason: 'Attribution automatique Smart Assign (charge minimale 3/15)',
      },
    ],
    messages: [
      {
        id: 'm1',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Bonjour le support ENO ! J\'ai 3 nouvelles commandes enregistrées sur Cotonou dont CMD-1048.',
        sentAt: '10:15',
      },
      {
        id: 'm2',
        sender: 'BOT',
        senderName: 'Assistant IA ENO',
        text: 'Bonjour Afrimarket ! Vos commandes sont en cours de répartition auprès de notre pôle télévente. Vos clients seront joints sous 15 minutes.',
        sentAt: '10:16',
      },
      {
        id: 'm-int-1',
        sender: 'AGENT',
        senderName: 'Sarah A. (Closeuse)',
        text: 'Client de CMD-1048 confirmé au téléphone. Très réactif, prêt avec le montant exact.',
        sentAt: '10:38',
        isInternalNote: true,
      },
      {
        id: 'm3',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Super travail ! Quel est le délai moyen pour le virement MTN Money de 500 000 FCFA demandé ce matin ?',
        sentAt: '11:42',
      },
      {
        id: 'm-int-2',
        sender: 'PDG',
        senderName: 'Jude S. (PDG)',
        text: 'Demande de retrait WD-2048 validée côté trésorerie. Virement en cours d\'émission par LeekPay/MTN.',
        sentAt: '11:45',
        isInternalNote: true,
      },
    ],
  },
  {
    id: 'conv-2',
    partnerId: 'p3',
    partnerName: 'Marie Dossou',
    companyName: 'Dossou Fashion (CI)',
    phone: '+225 07 45 12 30 89',
    lastMessage: 'J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement des fonds.',
    lastMessageAt: 'Il y a 25 min',
    unreadCount: 0,
    status: 'WAITING',
    priority: 'HIGH',
    assignedAgentId: 'usr-pdg',
    assignedAgentName: 'Jude S. (PDG)',
    assignedAgentRole: 'Direction Générale',
    relatedOrderNumber: 'CMD-BJ5K9L2M',
    firstResponseTimeMinutes: 5,
    avgResponseTimeMinutes: 12,
    slaStatus: 'NORMAL',
    assignmentHistory: [
      {
        id: 'ah-2',
        assignedToName: 'Sarah A.',
        assignedToRole: 'Closeuse',
        timestamp: '03 sept. — 15:00',
        reason: 'Smart Assign',
      },
      {
        id: 'ah-3',
        assignedToName: 'Jude S. (PDG)',
        assignedToRole: 'Direction',
        timestamp: '04 sept. — 10:10',
        reason: 'Escalade financière : arbitrage USDT international',
      },
    ],
    messages: [
      {
        id: 'm21',
        sender: 'PARTNER',
        senderName: 'Marie Dossou',
        text: 'Bonjour Monsieur, mes fonds de ventes à Cotonou sont prêts à être retirés en USDT.',
        sentAt: '10:10',
      },
      {
        id: 'm22',
        sender: 'PARTNER',
        senderName: 'Marie Dossou',
        text: 'J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement des fonds.',
        sentAt: '10:15',
        attachmentName: 'releve_ventes_dossou_aout.pdf',
        attachmentType: 'PDF',
        attachmentSize: '412 KB',
      },
      {
        id: 'm23',
        sender: 'PDG',
        senderName: 'Jude S. (PDG)',
        text: 'Bien reçu Madame Dossou. Notre responsable de trésorerie procède à la vérification du hash de transaction USDT.',
        sentAt: '10:22',
      },
    ],
  },
  {
    id: 'conv-3',
    partnerId: 'p2',
    partnerName: 'Marius Houngbo',
    companyName: 'Bénin Shop Électro',
    phone: '+229 01 93 83 79 06',
    lastMessage: 'Concernant l\'écart de 5 000 FCFA sur la commande CMD-1047, c\'est validé.',
    lastMessageAt: 'Il y a 1h',
    unreadCount: 1,
    status: 'IN_PROGRESS',
    priority: 'NORMAL',
    assignedAgentId: 'tm-1',
    assignedAgentName: 'Jean-Baptiste AGOSSOU',
    assignedAgentRole: 'Responsable Trésorerie',
    relatedOrderNumber: 'CMD-1047',
    firstResponseTimeMinutes: 2,
    avgResponseTimeMinutes: 5,
    slaStatus: 'NORMAL',
    assignmentHistory: [
      {
        id: 'ah-4',
        assignedToName: 'Jean-Baptiste AGOSSOU',
        assignedToRole: 'Responsable Trésorerie',
        timestamp: '04 sept. — 09:42',
        reason: 'Affectation manuelle pour clarification écart de remise',
      },
    ],
    messages: [
      {
        id: 'm31',
        sender: 'TREASURY',
        senderName: 'Jean-Baptiste AGOSSOU (Trésorier)',
        text: 'Bonjour M. Houngbo, le livreur Wilfried nous signale un encaissement de 20 000 FCFA au lieu de 25 000 FCFA sur CMD-1047. Pouvez-vous confirmer ?',
        sentAt: '09:42',
      },
      {
        id: 'm32',
        sender: 'PARTNER',
        senderName: 'Marius Houngbo (Bénin Shop)',
        text: 'Concernant l\'écart de 5 000 FCFA sur la commande CMD-1047, c\'est validé. Le client a retiré un produit en commun accord.',
        sentAt: '09:48',
      },
    ],
  },
  {
    id: 'conv-4',
    partnerId: 'p4',
    partnerName: 'Ablam AMEGAN',
    companyName: 'Lokossa Tech Store',
    phone: '+229 01 62 88 99 00',
    lastMessage: 'Nous avons corrigé l\'emballage de protection sur nos colis électroniques.',
    lastMessageAt: 'Hier 17:15',
    unreadCount: 0,
    status: 'ESCALATED',
    priority: 'HIGH',
    assignedAgentId: 'usr-pdg',
    assignedAgentName: 'Jude S. (PDG)',
    assignedAgentRole: 'Direction Générale',
    relatedOrderNumber: 'CMD-1045',
    firstResponseTimeMinutes: 8,
    avgResponseTimeMinutes: 15,
    slaStatus: 'NORMAL',
    assignmentHistory: [
      {
        id: 'ah-5',
        assignedToName: 'Jude S. (PDG)',
        assignedToRole: 'Direction',
        timestamp: '03 sept. — 14:12',
        reason: 'Escalade suite à suspension de compte marchand',
      },
    ],
    messages: [
      {
        id: 'm41',
        sender: 'PARTNER',
        senderName: 'Ablam AMEGAN',
        text: 'Bonjour Monsieur le Directeur, nous avons pris acte de la suspension. Nous avons corrigé l\'emballage de protection sur nos colis électroniques.',
        sentAt: 'Hier 17:15',
        attachmentName: 'photo_nouveaux_emballages.jpg',
        attachmentType: 'IMAGE',
        attachmentSize: '1.8 MB',
      },
    ],
  },
  {
    id: 'conv-5',
    partnerId: 'p1',
    partnerName: 'Jude Sina',
    companyName: 'Afrimarket',
    phone: '+229 01 97 36 29 06',
    lastMessage: 'Merci pour la confirmation rapide du client de Calavi ! Super closing.',
    lastMessageAt: 'Hier 16:30',
    unreadCount: 0,
    status: 'RESOLVED',
    priority: 'LOW',
    assignedAgentId: 'cls-2',
    assignedAgentName: 'Chimène A.',
    assignedAgentRole: 'Closeuse Senior',
    relatedOrderNumber: 'CMD-BJ3M4N5K',
    firstResponseTimeMinutes: 3,
    avgResponseTimeMinutes: 6,
    slaStatus: 'NORMAL',
    messages: [
      {
        id: 'm51',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Merci pour la confirmation rapide du client de Calavi ! Super closing.',
        sentAt: 'Hier 16:30',
      },
    ],
  },
];

// ⚠️ Alertes Intelligentes du Centre d'Attention
export const initialAgencyAlerts: AgencyAlert[] = [
  {
    id: 'alt-1',
    severity: 'CRITICAL',
    title: '3 demandes de retrait nécessitent votre arbitrage',
    description: 'Montant cumulé : 612 400 F CFA en attente de déblocage (MTN Money & USDT TRC-20).',
    actionLabel: 'Arbitrer les retraits',
    actionHref: '/admin/finances',
    count: 3,
  },
  {
    id: 'alt-2',
    severity: 'WARNING',
    title: '1 client à rappeler en urgence',
    description: 'CMD-BJ9G0H1I (Afrimarket) — Injoignable au 1er appel, rappel programmé cet après-midi.',
    actionLabel: 'Voir la file closing',
    actionHref: '/admin/commandes',
    count: 1,
  },
  {
    id: 'alt-3',
    severity: 'INFO',
    title: 'Stock bas détecté : 1 produit sous le seuil critique',
    description: 'Pack Savon Noir & Curcuma (Bénin Shop) — Moins de 10 unités en entrepôt Cotonou.',
    actionLabel: 'Planifier ramassage',
    actionHref: '/admin/stocks',
    count: 1,
  },
];

// 💰 Grand Livre de Trésorerie (Journal Financier d'ENO)
export const initialTransactions: FinancialTransaction[] = [
  {
    id: 'tx-10482',
    txReference: 'TX-2026-0903-084',
    date: '2026-09-03 18:35',
    type: 'ENCAISSEMENT_COD',
    label: 'Encaissement COD Commande CMD-1041',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    orderNumber: 'CMD-1041',
    inflow: 38000,
    outflow: 0,
    balanceAfter: 14850000,
    status: 'COMPLETED',
    notes: 'Espèces encaissées par Rachad et transmises au Hub Cadjehoun.',
  },
  {
    id: 'tx-10481',
    txReference: 'TX-2026-0903-083',
    date: '2026-09-03 18:36',
    type: 'COMMISSION_ENO',
    label: 'Commission ENO (Livraison 2 000 + Closing 800)',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    orderNumber: 'CMD-1041',
    inflow: 2800,
    outflow: 0,
    balanceAfter: 14850000,
    status: 'COMPLETED',
    notes: 'Revenu net agence prélevé automatiquement.',
  },
  {
    id: 'tx-10480',
    txReference: 'TX-2026-0903-082',
    date: '2026-09-03 18:36',
    type: 'CREDIT_MARCHAND',
    label: 'Crédit Solde Afrimarket (Net marchand 35 200 FCFA)',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    orderNumber: 'CMD-1041',
    inflow: 0,
    outflow: 35200,
    balanceAfter: 14814800,
    status: 'COMPLETED',
    notes: 'Solde e-commerçant crédité et disponible pour retrait.',
  },
  {
    id: 'tx-10479',
    txReference: 'TX-2026-0903-079',
    date: '2026-09-03 16:40',
    type: 'RETRAIT',
    label: 'Retrait Marchand Bénin Shop (MTN Mobile Money)',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    inflow: 0,
    outflow: 120000,
    balanceAfter: 14812000,
    status: 'COMPLETED',
    notes: 'Virement validé par la Direction. Réf: MTN-TX-984214.',
  },
  {
    id: 'tx-10478',
    txReference: 'TX-2026-0903-075',
    date: '2026-09-03 14:15',
    type: 'DEPENSE',
    label: 'Carburant Flotte Coursiers Hub Cotonou',
    inflow: 0,
    outflow: 45000,
    balanceAfter: 14932000,
    status: 'COMPLETED',
    notes: 'Avance carburant 9 motos de tournée.',
  },
  {
    id: 'tx-10477',
    txReference: 'TX-2026-0903-068',
    date: '2026-09-03 11:30',
    type: 'ENCAISSEMENT_COD',
    label: 'Encaissement COD Commande CMD-1035',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion',
    livreurId: 'liv-2',
    livreurName: 'Wilfried HOUNGBO',
    orderNumber: 'CMD-1035',
    inflow: 65000,
    outflow: 0,
    balanceAfter: 14977000,
    status: 'COMPLETED',
    notes: 'Espèces encaissées à Fidjrossè.',
  },
];

// 💵 Encaissements COD individuels par commande livrée
export const initialCodCollections: CodCollection[] = [
  {
    orderId: 'cmd_001',
    orderNumber: 'CMD-1048',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    clientName: 'Marcelle AGUESSY',
    clientPhone: '+229 01 97 45 12 00',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    expectedAmount: 38000,
    collectedAmount: 38000,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'HELD_BY_DRIVER',
    deliveredAt: '2026-09-04 10:15',
  },
  {
    orderId: 'cmd_002',
    orderNumber: 'CMD-1047',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    clientName: 'Gérard HOUNSOU',
    clientPhone: '+229 01 66 33 22 11',
    livreurId: 'liv-2',
    livreurName: 'Wilfried HOUNGBO',
    expectedAmount: 25000,
    collectedAmount: 20000,
    discrepancy: -5000,
    discrepancyJustification: 'Client a retiré un flacon cosmétique après accord téléphonique du marchand.',
    collectionStatus: 'DISCREPANCY_FLAGGED',
    remittanceStatus: 'DISCREPANCY_DETECTED',
    deliveredAt: '2026-09-04 09:40',
  },
  {
    orderId: 'cmd_003',
    orderNumber: 'CMD-1046',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion',
    clientName: 'Nadège KIKI',
    clientPhone: '+229 01 95 11 22 33',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    expectedAmount: 42000,
    collectedAmount: 42000,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'HELD_BY_DRIVER',
    deliveredAt: '2026-09-04 09:20',
  },
  {
    orderId: 'cmd_004',
    orderNumber: 'CMD-1045',
    partnerId: 'p4',
    partnerName: 'Lokossa Tech Store',
    clientName: 'Ablam AMEGAN',
    clientPhone: '+229 01 62 88 99 00',
    livreurId: 'liv-3',
    livreurName: 'Boris TCHICAYA',
    expectedAmount: 75000,
    collectedAmount: 75000,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'REMITTED',
    deliveredAt: '2026-09-03 17:30',
    remittanceId: 'rem-102',
  },
  {
    orderId: 'cmd_005',
    orderNumber: 'CMD-1044',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    clientName: 'Diane SOSSOU',
    clientPhone: '+229 01 93 11 00 22',
    livreurId: 'liv-3',
    livreurName: 'Boris TCHICAYA',
    expectedAmount: 18500,
    collectedAmount: 18500,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'VALIDATED',
    deliveredAt: '2026-09-03 16:10',
    remittanceId: 'rem-101',
  },
];

// 🏦 Remises de Fonds des Livreurs (Dépôt d'espèces à l'agence)
export const initialCodRemittances: CodRemittance[] = [
  {
    id: 'rem-103',
    reference: 'REM-2026-0904-003',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    amountExpected: 80000,
    amountDeclared: 80000,
    ordersCount: 2,
    orderIds: ['cmd_001', 'cmd_003'],
    period: 'Matinée du 04 Septembre 2026',
    createdAt: '2026-09-04 10:45',
    status: 'PENDING_VALIDATION',
    notes: 'Remise en espèces déposée à la caisse Hub Cadjehoun.',
  },
  {
    id: 'rem-102',
    reference: 'REM-2026-0903-002',
    livreurId: 'liv-3',
    livreurName: 'Boris TCHICAYA',
    amountExpected: 250000,
    amountDeclared: 250000,
    amountValidated: 250000,
    discrepancyAmount: 0,
    ordersCount: 8,
    orderIds: ['cmd_004', 'cmd_005'],
    period: 'Tournée Après-midi 03 Septembre',
    createdAt: '2026-09-03 18:30',
    validatedAt: '2026-09-03 18:45',
    validatedBy: 'Direction ENO (Super Admin)',
    status: 'VALIDATED',
    notes: 'Comptage physique effectué et validé au coffre-fort.',
  },
  {
    id: 'rem-101',
    reference: 'REM-2026-0902-001',
    livreurId: 'liv-2',
    livreurName: 'Wilfried HOUNGBO',
    amountExpected: 300000,
    amountDeclared: 295000,
    amountValidated: 295000,
    discrepancyAmount: -5000,
    discrepancyJustification: 'Écart de 5 000 FCFA sur commande CMD-1047 justifié par le marchand.',
    ordersCount: 11,
    orderIds: ['cmd_002'],
    period: 'Journée du 02 Septembre 2026',
    createdAt: '2026-09-02 19:10',
    validatedAt: '2026-09-02 19:30',
    validatedBy: 'Direction ENO (Super Admin)',
    status: 'PARTIALLY_VALIDATED',
    notes: 'Écart accepté après vérification avec le commerçant Bénin Shop.',
  },
];

// 📜 Journal d'Audit Financier Non-Destructif
export const initialFinancialAuditLogs: FinancialAuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-04 10:45',
    action: 'Remise de fonds déclarée',
    actor: 'Rachad ADECHINA (Livreur)',
    targetType: 'REMITTANCE',
    targetId: 'REM-2026-0904-003',
    amount: 80000,
    details: 'Déclaration de remise d\'espèces de 80 000 FCFA sur 2 commandes.',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-04 09:40',
    action: 'Écart d\'encaissement signalé',
    actor: 'Wilfried HOUNGBO (Livreur)',
    targetType: 'DISCREPANCY',
    targetId: 'CMD-1047',
    amount: -5000,
    details: 'Montant attendu: 25 000 FCFA, collecté: 20 000 FCFA. Justification: modification marchand.',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-04 09:30',
    action: 'Demande de retrait créée & solde réservé',
    actor: 'Afrimarket (E-commerçant)',
    targetType: 'WITHDRAWAL',
    targetId: 'WD-2048',
    amount: 500000,
    details: 'Demande LeekPay de 500 000 FCFA. 500 000 FCFA déplacés en montant réservé.',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-03 18:45',
    action: 'Remise de fonds validée',
    actor: 'Direction ENO (Super Admin)',
    targetType: 'REMITTANCE',
    targetId: 'REM-2026-0903-002',
    amount: 250000,
    details: 'Validation intégrale sans écart de 250 000 FCFA (Boris TCHICAYA).',
  },
  {
    id: 'aud-5',
    timestamp: '2026-09-02 16:40',
    action: 'Virement de retrait exécuté & archivé',
    actor: 'Direction ENO (Super Admin)',
    targetType: 'WITHDRAWAL',
    targetId: 'WD-2045',
    amount: 120000,
    details: 'Règlement LeekPay validé. Réf: LK-PAY-984214-BJ.',
  },
];

// 👥 Responsables de Trésorerie (Treasury Managers)
export const initialTreasuryManagers: TreasuryManagerProfile[] = [
  {
    id: 'tm-1',
    firstName: 'Jean-Baptiste',
    lastName: 'AGOSSOU',
    name: 'Jean-Baptiste AGOSSOU',
    email: 'jb.agossou@enolivraison.com',
    phone: '+229 01 97 12 34 56',
    zone: 'Hub Central Cotonou (Cadjehoun)',
    status: 'ACTIF',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-06-15 08:30',
    lastActiveAt: 'Il y a 5 min',
    remittancesReceivedCount: 48,
    totalFundsReceived: 8450000,
    discrepanciesFlaggedCount: 2,
    notes: 'Responsable principal de la caisse physique et des remises terrain au Hub Central.',
  },
  {
    id: 'tm-2',
    firstName: 'Sandrine',
    lastName: 'MENSAH',
    name: 'Sandrine MENSAH',
    email: 'sandrine.mensah@enolivraison.com',
    phone: '+229 01 66 88 99 00',
    zone: 'Hub Secondaire Calavi (Arconville)',
    status: 'ACTIF',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-07-01 09:00',
    lastActiveAt: 'Il y a 22 min',
    remittancesReceivedCount: 31,
    totalFundsReceived: 4720000,
    discrepanciesFlaggedCount: 1,
    notes: 'En charge du contrôle physique des fonds collectés par la flotte Calavi/Akassato.',
  },
  {
    id: 'tm-3',
    firstName: 'Armand',
    lastName: 'KOUASSI',
    name: 'Armand KOUASSI',
    email: 'armand.kouassi@enolivraison.com',
    phone: '+229 01 95 44 33 22',
    zone: 'Hub Porto-Novo',
    status: 'EN_PAUSE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-08-10 10:15',
    lastActiveAt: 'Hier à 17:30',
    remittancesReceivedCount: 14,
    totalFundsReceived: 2030000,
    discrepanciesFlaggedCount: 0,
    notes: 'En congé de relève, permanence assurée par le Hub Central.',
  },
];

// ==========================================
// 🛡️ MOCK DATA AUDIT GLOBAL & SESSIONS
// ==========================================

export const initialGlobalAuditLogs: GlobalAuditLog[] = [
  {
    id: 'aud-glob-001',
    timestamp: '04 sept. 2026 — 10:42:18',
    isoDate: '2026-09-04T10:42:18',
    actor: {
      id: 'tm-1',
      name: 'Jean-Baptiste AGOSSOU',
      role: 'Responsable de trésorerie',
      type: 'USER',
    },
    action: 'REMITTANCE_VALIDATED',
    actionLabel: 'A validé la remise physique',
    module: 'TRESORERIE',
    entityType: 'REMITTANCE',
    entityId: 'rem-103',
    entityReference: 'RM-1045',
    severity: 'INFO',
    result: 'SUCCESS',
    description: 'A validé la remise RM-1045 de 150 000 FCFA au coffre-fort sans écart.',
    financeTxRef: 'TX-2026-0903-084',
    ipAddress: '41.85.160.12',
    sessionId: 'sess-849201',
  },
  {
    id: 'aud-glob-002',
    timestamp: '04 sept. 2026 — 10:38:05',
    isoDate: '2026-09-04T10:38:05',
    actor: {
      id: 'cls-1',
      name: 'Sarah A.',
      role: 'Closeuse',
      type: 'USER',
    },
    action: 'ORDER_CONFIRMED',
    actionLabel: 'A confirmé la commande',
    module: 'COMMANDES',
    entityType: 'ORDER',
    entityId: 'o1',
    entityReference: 'CMD-1048',
    severity: 'INFO',
    result: 'SUCCESS',
    description: 'A confirmé la commande CMD-1048 après 1 appel téléphonique (client prêt avec le montant exact).',
    beforeState: { status: 'EN_ATTENTE', callCount: 0 },
    afterState: { status: 'CONFIRMEE', callCount: 1, deliveryTimeSlot: '14h00 - 16h00' },
    ipAddress: '197.234.218.44',
  },
  {
    id: 'aud-glob-003',
    timestamp: '04 sept. 2026 — 10:31:40',
    isoDate: '2026-09-04T10:31:40',
    actor: {
      id: 'usr-pdg',
      name: 'Jude S. (PDG)',
      role: 'Super Admin',
      type: 'USER',
    },
    action: 'USER_CREATED',
    actionLabel: 'A créé un nouvel utilisateur',
    module: 'UTILISATEURS',
    entityType: 'USER',
    entityId: 'cls-4',
    entityReference: 'USR-04 (Marie K.)',
    severity: 'WARNING',
    result: 'SUCCESS',
    description: 'Création du compte closeuse pour Marie KODJO avec permissions standard.',
    afterState: { email: 'marie.k@enolivraison.com', role: 'CLOSER', status: 'ACTIF' },
    isSensitive: true,
    ipAddress: '41.85.160.22',
  },
  {
    id: 'aud-glob-004',
    timestamp: '04 sept. 2026 — 10:24:12',
    isoDate: '2026-09-04T10:24:12',
    actor: {
      id: 'liv-1',
      name: 'Rachad ADECHINA',
      role: 'Livreur',
      type: 'USER',
    },
    action: 'DRIVER_AVAILABILITY_CHANGED',
    actionLabel: 'A changé sa disponibilité',
    module: 'LIVREURS',
    entityType: 'LIVREUR',
    entityId: 'liv-1',
    entityReference: 'LIV-01',
    severity: 'INFO',
    result: 'SUCCESS',
    description: 'A changé son statut de disponibilité → Disponible pour tournées Littoral.',
    beforeState: { availabilityStatus: 'PAUSED' },
    afterState: { availabilityStatus: 'AVAILABLE' },
    ipAddress: '197.234.219.88',
  },
  {
    id: 'aud-glob-005',
    timestamp: '04 sept. 2026 — 10:15:30',
    isoDate: '2026-09-04T10:15:30',
    actor: {
      id: 'sys-smart-assign',
      name: 'Système',
      role: 'Automatisation des attributions',
      type: 'SYSTEM',
    },
    action: 'AUTOMATIC_ASSIGNMENT_EXECUTED',
    actionLabel: 'Attribution automatique exécutée',
    module: 'AUTOMATISATION',
    entityType: 'ORDER',
    entityId: 'o2',
    entityReference: 'CMD-1047',
    severity: 'INFO',
    result: 'SUCCESS',
    description: 'A attribué automatiquement la commande CMD-1047 à Sarah A.',
    reason: 'Disponibilité confirmée (En ligne), capacité disponible (3/15 commandes actives), charge minimale parmi les candidates éligibles, Round Robin utilisé comme tie-breaker.',
  },
  {
    id: 'aud-glob-006',
    timestamp: '04 sept. 2026 — 09:55:10',
    isoDate: '2026-09-04T09:55:10',
    actor: {
      id: 'sys-security',
      name: 'Système Sécurité',
      role: 'WAF & Autorisation',
      type: 'SYSTEM',
    },
    action: 'PERMISSION_UPDATE_BLOCKED',
    actionLabel: 'Tentative d\'action bloquée',
    module: 'AUTH',
    entityType: 'RULE',
    entityId: 'perm-sec-01',
    entityReference: 'ROLE-CLOSER',
    severity: 'CRITICAL',
    result: 'BLOCKED',
    description: 'Tentative d\'élévation de privilèges ou modification de droits financiers non autorisée.',
    ipAddress: '197.234.221.14',
    isSensitive: true,
  },
  {
    id: 'aud-glob-007',
    timestamp: '04 sept. 2026 — 09:40:22',
    isoDate: '2026-09-04T09:40:22',
    actor: {
      id: 'liv-2',
      name: 'Wilfried HOUNGBO',
      role: 'Livreur',
      type: 'USER',
    },
    action: 'DISCREPANCY_FLAGGED',
    actionLabel: 'Écart d\'encaissement signalé',
    module: 'TRESORERIE',
    entityType: 'ORDER',
    entityId: 'cmd_002',
    entityReference: 'CMD-1047',
    severity: 'WARNING',
    result: 'FAILED',
    description: 'A déclaré un encaissement partiel de 20 000 FCFA sur 25 000 FCFA attendus (écart de -5 000 FCFA signalé sur CMD-1047).',
    reason: 'Client a retiré un produit après accord téléphonique direct avec la boutique partenaire Bénin Shop.',
    financeTxRef: 'TX-2026-0903-079',
    ipAddress: '197.234.219.92',
  },
  {
    id: 'aud-glob-008',
    timestamp: '04 sept. 2026 — 09:12:00',
    isoDate: '2026-09-04T09:12:00',
    actor: {
      id: 'usr-pdg',
      name: 'Jude S. (PDG)',
      role: 'Super Admin',
      type: 'USER',
    },
    action: 'CAPACITY_UPDATED',
    actionLabel: 'Modification de capacité livreur',
    module: 'LIVREURS',
    entityType: 'LIVREUR',
    entityId: 'liv-3',
    entityReference: 'LIV-03 (Gaston B.)',
    severity: 'WARNING',
    result: 'SUCCESS',
    description: 'Ajustement de la capacité maximale de tournée pour absorber le flux Littoral.',
    beforeState: { maxActiveCapacity: 8 },
    afterState: { maxActiveCapacity: 12 },
    isSensitive: false,
    ipAddress: '41.85.160.22',
  },
  {
    id: 'aud-glob-009',
    timestamp: '04 sept. 2026 — 08:45:10',
    isoDate: '2026-09-04T08:45:10',
    actor: {
      id: 'usr-pdg',
      name: 'Jude S. (PDG)',
      role: 'Super Admin',
      type: 'USER',
    },
    action: 'SETTING_COMMISSION_UPDATED',
    actionLabel: 'Modification des paramètres de commission',
    module: 'PARAMETRES',
    entityType: 'SETTING',
    entityId: 'conf-comm-global',
    entityReference: 'CONF-FIN-01',
    severity: 'CRITICAL',
    result: 'SUCCESS',
    description: 'Mise à jour de la grille tarifaire de livraison standard et commission closing.',
    beforeState: { commissionClosing: 800, deliveryStandardFee: 2000 },
    afterState: { commissionClosing: 1000, deliveryStandardFee: 2200 },
    isSensitive: true,
    ipAddress: '41.85.160.22',
  },
  {
    id: 'aud-glob-010',
    timestamp: '04 sept. 2026 — 08:15:00',
    isoDate: '2026-09-04T08:15:00',
    actor: {
      id: 'usr-pdg',
      name: 'Jude S. (PDG)',
      role: 'Super Admin',
      type: 'USER',
    },
    action: 'LOGIN_SUCCESS',
    actionLabel: 'Connexion réussie',
    module: 'AUTH',
    entityType: 'SESSION',
    entityId: 'sess-984210',
    entityReference: 'SESS-PDG-01',
    severity: 'INFO',
    result: 'SUCCESS',
    description: 'Authentification multifacteur validée depuis macOS Safari.',
    ipAddress: '41.85.160.22',
    sessionId: 'sess-984210',
  },
  {
    id: 'aud-glob-011',
    timestamp: '03 sept. 2026 — 18:45:00',
    isoDate: '2026-09-03T18:45:00',
    actor: {
      id: 'usr-pdg',
      name: 'Jude S. (PDG)',
      role: 'Super Admin',
      type: 'USER',
    },
    action: 'WITHDRAWAL_APPROVED',
    actionLabel: 'A approuvé un retrait e-commerçant',
    module: 'FINANCES',
    entityType: 'PAYOUT',
    entityId: 'wd-2048',
    entityReference: 'WD-2048',
    severity: 'CRITICAL',
    result: 'SUCCESS',
    description: 'A approuvé le virement LeekPay de 500 000 FCFA en faveur d\'Afrimarket.',
    financeTxRef: 'TX-2026-0903-082',
    isSensitive: true,
    ipAddress: '41.85.160.22',
  },
  {
    id: 'aud-glob-012',
    timestamp: '03 sept. 2026 — 16:30:15',
    isoDate: '2026-09-03T16:30:15',
    actor: {
      id: 'sys-notify',
      name: 'Système',
      role: 'Centre de Notifications',
      type: 'SYSTEM',
    },
    action: 'NOTIFICATION_SENT',
    actionLabel: 'Notification broadcast envoyée',
    module: 'AUTOMATISATION',
    entityType: 'SYSTEM',
    entityId: 'notif-bc-01',
    entityReference: 'NOTIF-CMD-ALERT',
    severity: 'INFO',
    result: 'SUCCESS',
    description: 'Alerte temps réel envoyée aux livreurs de zone Calavi pour prise en charge prioritaire.',
  },
  {
    id: 'aud-glob-013',
    timestamp: '03 sept. 2026 — 14:10:00',
    isoDate: '2026-09-03T14:10:00',
    actor: {
      id: 'usr-pdg',
      name: 'Jude S. (PDG)',
      role: 'Super Admin',
      type: 'USER',
    },
    action: 'MERCHANT_SUSPENDED',
    actionLabel: 'A suspendu un e-commerçant',
    module: 'ECOMMERCE',
    entityType: 'PARTNER',
    entityId: 'p4',
    entityReference: 'Lokossa Tech',
    severity: 'CRITICAL',
    result: 'SUCCESS',
    description: 'Suspension temporaire pour non-conformité répétée sur l\'emballage colis.',
    beforeState: { status: 'ACTIVE' },
    afterState: { status: 'SUSPENDED', suspensionReason: 'Non-conformité emballage' },
    isSensitive: true,
    ipAddress: '41.85.160.22',
  },
];

export const initialAuditSessions: AuditSessionLog[] = [
  {
    id: 'sess-01',
    userId: 'usr-pdg',
    userName: 'Jude S. (PDG)',
    userRole: 'Super Admin',
    ipAddress: '41.85.160.22',
    device: 'Apple MacBook Pro',
    browser: 'Safari 18.0 (macOS)',
    location: 'Cotonou, Bénin',
    loginAt: '04 sept. 2026 — 08:15',
    lastActiveAt: 'Il y a 1 min',
    status: 'ACTIVE',
  },
  {
    id: 'sess-02',
    userId: 'tm-1',
    userName: 'Jean-Baptiste AGOSSOU',
    userRole: 'Responsable de trésorerie',
    ipAddress: '41.85.160.12',
    device: 'Lenovo ThinkPad',
    browser: 'Chrome 128.0 (Windows)',
    location: 'Hub Central Cadjehoun, Bénin',
    loginAt: '04 sept. 2026 — 08:30',
    lastActiveAt: 'Il y a 4 min',
    status: 'ACTIVE',
  },
  {
    id: 'sess-03',
    userId: 'cls-1',
    userName: 'Inès T.',
    userRole: 'Closeuse',
    ipAddress: '197.234.218.44',
    device: 'Dell Latitude',
    browser: 'Chrome 128.0 (Windows)',
    location: 'Cotonou, Bénin',
    loginAt: '04 sept. 2026 — 08:00',
    lastActiveAt: 'Il y a 12 min',
    status: 'ACTIVE',
  },
  {
    id: 'sess-04',
    userId: 'usr-unknown',
    userName: 'Tentative inconnue',
    userRole: 'Inconnu',
    ipAddress: '197.234.221.14',
    device: 'Linux Desktop',
    browser: 'Firefox 130.0',
    location: 'Lagos, Nigeria',
    loginAt: '04 sept. 2026 — 09:54',
    lastActiveAt: '04 sept. 2026 — 09:55',
    status: 'FAILED_ATTEMPT',
    failureReason: 'Mot de passe erroné (3 tentatives infructueuses)',
  },
];

// ========================================================
// 🔔 MATRICE DE TRAÇABILITÉ DES NOTIFICATIONS & ALERTES (NOT-001 à NOT-022)
// ========================================================
export const initialPlatformNotifications: PlatformNotification[] = [
  {
    id: 'notif-001',
    category: 'COMMANDES',
    priority: 'INFO',
    title: 'Nouvelle commande reçue',
    description: 'Marcelle AGUESSY a commandé le Pack Éclat Suprême (38 000 FCFA). Télévente en attente.',
    isRead: false,
    createdAt: 'Il y a 4 min',
    isoDate: '2026-09-04T10:45:00',
    referenceId: 'CMD-1048',
    referenceType: 'ORDER',
    actionUrl: '/admin/commandes/cmd_001',
    actionLabel: 'Voir la commande',
    isAlert: false,
  },
  {
    id: 'notif-002',
    category: 'COMMANDES',
    priority: 'URGENT',
    title: 'Commande bloquée en télévente',
    description: 'CMD-1047 (Bénin Shop) — Client injoignable après 2 tentatives d\'appel par Sarah K.',
    isRead: false,
    createdAt: 'Il y a 12 min',
    isoDate: '2026-09-04T10:37:00',
    referenceId: 'CMD-1047',
    referenceType: 'ORDER',
    actionUrl: '/admin/commandes/cmd_002',
    actionLabel: 'Traiter le closing',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-003',
    category: 'COMMANDES',
    priority: 'INFO',
    title: 'Commande annulée par le client',
    description: 'CMD-1045 (Lokossa Tech) — Annulation client enregistrée. Motif : doublon de commande.',
    isRead: true,
    createdAt: 'Il y a 45 min',
    isoDate: '2026-09-04T10:04:00',
    referenceId: 'CMD-1045',
    referenceType: 'ORDER',
    actionUrl: '/admin/commandes',
    actionLabel: 'Consulter la commande',
    isAlert: false,
  },
  {
    id: 'notif-004',
    category: 'LIVRAISONS',
    priority: 'INFO',
    title: 'Livraison terminée & COD encaissé',
    description: 'Colis CMD-1048 remis à Cadjehoun par Rachad A. Encaissement COD : 38 000 FCFA.',
    isRead: true,
    createdAt: 'Il y a 1h',
    isoDate: '2026-09-04T09:45:00',
    referenceId: 'CMD-1048',
    referenceType: 'DELIVERY',
    actionUrl: '/admin/livraisons',
    actionLabel: 'Voir la livraison',
    isAlert: false,
  },
  {
    id: 'notif-005',
    category: 'LIVRAISONS',
    priority: 'URGENT',
    title: 'Livraison en retard (> 90 min)',
    description: 'CMD-BJ5K9L2M (Dossou Fashion) vers Ouando — Coursier ralenti par un trafic dense.',
    isRead: false,
    createdAt: 'Il y a 15 min',
    isoDate: '2026-09-04T10:34:00',
    referenceId: 'CMD-BJ5K9L2M',
    referenceType: 'DELIVERY',
    actionUrl: '/admin/livraisons',
    actionLabel: 'Suivre la tournée',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-006',
    category: 'LIVRAISONS',
    priority: 'URGENT',
    title: 'Livraison échouée / Client absent',
    description: 'CMD-1046 à Akpakpa — Client indisponible au point de rendez-vous. Reprogrammation nécessaire.',
    isRead: false,
    createdAt: 'Il y a 22 min',
    isoDate: '2026-09-04T10:27:00',
    referenceId: 'CMD-1046',
    referenceType: 'DELIVERY',
    actionUrl: '/admin/retours',
    actionLabel: 'Gérer le litige',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-007',
    category: 'LIVREURS',
    priority: 'URGENT',
    title: 'Plafond d\'espèces coursier atteint',
    description: 'Rachad ADECHINA détient 150 000 FCFA en espèces non encore remises au coffre.',
    isRead: false,
    createdAt: 'Il y a 8 min',
    isoDate: '2026-09-04T10:41:00',
    referenceId: 'liv-1',
    referenceType: 'DRIVER',
    actionUrl: '/admin/livreurs/liv-1',
    actionLabel: 'Voir le livreur',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-008',
    category: 'ECOMMERCE',
    priority: 'INFO',
    title: 'Nouveau marchand inscrit',
    description: 'La boutique Lokossa Tech Store a rejoint le réseau logistique ENO Livraison.',
    isRead: true,
    createdAt: 'Hier à 14:00',
    isoDate: '2026-09-03T14:00:00',
    referenceId: 'p4',
    referenceType: 'MERCHANT',
    actionUrl: '/admin/partenaires/p4',
    actionLabel: 'Voir le profil',
    isAlert: false,
  },
  {
    id: 'notif-009',
    category: 'ECOMMERCE',
    priority: 'URGENT',
    title: 'Avertissement qualité emballage marchand',
    description: 'Signalement qualité émis pour Lokossa Tech suite à une protection de colis non conforme.',
    isRead: false,
    createdAt: 'Hier à 14:10',
    isoDate: '2026-09-03T14:10:00',
    referenceId: 'p4',
    referenceType: 'MERCHANT',
    actionUrl: '/admin/partenaires/p4',
    actionLabel: 'Examiner le partenaire',
    isAlert: true,
    alertStatus: 'ACKNOWLEDGED',
  },
  {
    id: 'notif-010',
    category: 'CONVERSATIONS',
    priority: 'INFO',
    title: 'Nouveau message support marchand',
    description: 'Dossou Fashion : "J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement."',
    isRead: false,
    createdAt: 'Il y a 25 min',
    isoDate: '2026-09-04T10:24:00',
    referenceId: 'conv-2',
    referenceType: 'CONVERSATION',
    actionUrl: '/admin/conversations',
    actionLabel: 'Répondre',
    isAlert: false,
  },
  {
    id: 'notif-011',
    category: 'CONVERSATIONS',
    priority: 'URGENT',
    title: 'Conversation prioritaire avec pièce jointe',
    description: 'Afrimarket a transmis un relevé de vente et sollicite un arbitrage urgent.',
    isRead: false,
    createdAt: 'Il y a 3 min',
    isoDate: '2026-09-04T10:46:00',
    referenceId: 'conv-1',
    referenceType: 'CONVERSATION',
    actionUrl: '/admin/conversations',
    actionLabel: 'Ouvrir le fil',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-012',
    category: 'FINANCES',
    priority: 'URGENT',
    title: 'Demande de retrait en attente d\'arbitrage',
    description: 'Afrimarket sollicite un reversement de 500 000 FCFA via MTN Mobile Money.',
    isRead: false,
    createdAt: 'Il y a 32 min',
    isoDate: '2026-09-04T10:17:00',
    referenceId: 'WD-2048',
    referenceType: 'WITHDRAWAL',
    actionUrl: '/admin/retraits',
    actionLabel: 'Arbitrer le retrait',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-013',
    category: 'FINANCES',
    priority: 'INFO',
    title: 'Retrait validé par la Direction',
    description: 'Retrait WD-2048 de 500 000 FCFA validé. Ordre d\'émission transmis à l\'opérateur.',
    isRead: true,
    createdAt: 'Il y a 15 min',
    isoDate: '2026-09-04T10:34:00',
    referenceId: 'WD-2048',
    referenceType: 'WITHDRAWAL',
    actionUrl: '/admin/retraits',
    actionLabel: 'Voir le retrait',
    isAlert: false,
  },
  {
    id: 'notif-014',
    category: 'FINANCES',
    priority: 'INFO',
    title: 'Retrait exécuté & payé au marchand',
    description: 'Virement MTN Money de 120 000 FCFA pour Bénin Shop validé (Réf: MTN-984214).',
    isRead: true,
    createdAt: 'Hier à 16:40',
    isoDate: '2026-09-03T16:40:00',
    referenceId: 'WD-2047',
    referenceType: 'WITHDRAWAL',
    actionUrl: '/admin/retraits',
    actionLabel: 'Voir la quittance',
    isAlert: false,
  },
  {
    id: 'notif-015',
    category: 'FINANCES',
    priority: 'URGENT',
    title: 'Demande de retrait rejetée',
    description: 'Retrait WD-2044 rejeté : Solde marchand insuffisant au moment de la vérification.',
    isRead: true,
    createdAt: 'Hier à 11:20',
    isoDate: '2026-09-03T11:20:00',
    referenceId: 'WD-2044',
    referenceType: 'WITHDRAWAL',
    actionUrl: '/admin/retraits',
    actionLabel: 'Examiner le motif',
    isAlert: false,
  },
  {
    id: 'notif-016',
    category: 'FINANCES',
    priority: 'CRITICAL',
    title: 'Échec de paiement passerelle API',
    description: 'Échec de virement sur le transfert 360 000 FCFA USDT (Erreur Timeout passerelle).',
    isRead: false,
    createdAt: 'Il y a 50 min',
    isoDate: '2026-09-04T09:59:00',
    referenceId: 'TX-2026-0903-079',
    referenceType: 'TRANSACTION',
    actionUrl: '/admin/finances',
    actionLabel: 'Arbitrer la transaction',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-017',
    category: 'FINANCES',
    priority: 'CRITICAL',
    title: 'Écart de caisse sur remise coursier',
    description: 'Remise REM-003 : Écart de -5 000 FCFA constaté par le responsable de trésorerie sur tournée Wilfried H.',
    isRead: false,
    createdAt: 'Il y a 5 min',
    isoDate: '2026-09-04T10:44:00',
    referenceId: 'REM-2026-0904-003',
    referenceType: 'TRANSACTION',
    actionUrl: '/admin/tresorerie',
    actionLabel: 'Résoudre l\'écart',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-018',
    category: 'INCIDENTS',
    priority: 'URGENT',
    title: 'Incident circulation majeur Cotonou-Calavi',
    description: 'Embouteillage Carrefour IITA : 4 livraisons réorientées sur itinéraire de délestage.',
    isRead: false,
    createdAt: 'Il y a 10 min',
    isoDate: '2026-09-04T10:39:00',
    referenceId: 'INC-2026-0904-01',
    referenceType: 'INCIDENT',
    actionUrl: '/admin/livraisons',
    actionLabel: 'Voir l\'impact',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-019',
    category: 'INCIDENTS',
    priority: 'CRITICAL',
    title: 'Incident matériel : Panne moto coursier',
    description: 'Moto en panne Zone Porto-Novo avec 6 colis urgents à bord. Véhicule relais dépêché.',
    isRead: false,
    createdAt: 'Il y a 18 min',
    isoDate: '2026-09-04T10:31:00',
    referenceId: 'INC-2026-0904-02',
    referenceType: 'INCIDENT',
    actionUrl: '/admin/audit',
    actionLabel: 'Ouvrir le rapport d\'incident',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-020',
    category: 'SYSTEME',
    priority: 'CRITICAL',
    title: 'Erreur critique synchronisation Webhook',
    description: 'Échec répétitif (502 Bad Gateway) sur le webhook Shopify de la boutique Afrimarket.',
    isRead: false,
    createdAt: 'Il y a 35 min',
    isoDate: '2026-09-04T10:14:00',
    referenceId: 'SYS-ERR-502',
    referenceType: 'SYSTEM',
    actionUrl: '/admin/audit',
    actionLabel: 'Examiner les logs d\'audit',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
  {
    id: 'notif-021',
    category: 'SYSTEME',
    priority: 'CRITICAL',
    title: 'Alerte solde passerelle SMS transactionnels',
    description: 'Solde critique (< 50 crédits) pour l\'envoi des SMS automatiques de livraison aux clients.',
    isRead: true,
    createdAt: 'Hier à 18:00',
    isoDate: '2026-09-03T18:00:00',
    referenceId: 'SYS-SMS-GATEWAY',
    referenceType: 'SYSTEM',
    actionUrl: '/admin/parametres',
    actionLabel: 'Recharger les crédits',
    isAlert: false,
  },
  {
    id: 'notif-022',
    category: 'SYSTEME',
    priority: 'CRITICAL',
    title: 'Tentative d\'accès non autorisée détectée',
    description: '3 échecs de mot de passe consécutifs détectés depuis l\'IP 197.234.221.14 (Lagos, Nigeria).',
    isRead: false,
    createdAt: 'Il y a 55 min',
    isoDate: '2026-09-04T09:54:00',
    referenceId: 'SEC-ALERT-0954',
    referenceType: 'SYSTEM',
    actionUrl: '/admin/audit',
    actionLabel: 'Consulter l\'audit de sécurité',
    isAlert: true,
    alertStatus: 'ACTIVE',
  },
];

// ==========================================
// 🛡️ DÉFINITION DES RÔLES DE LA PLATEFORME
// ==========================================

export const platformRoles: RoleDefinition[] = [
  {
    id: 'PDG',
    label: 'Président Directeur Général (PDG)',
    category: 'DIRECTION',
    description: 'Accès souverain et gouvernance totale à tous les modules, finances, arbitrages et configurations.',
    color: '#0f172a',
    badgeBg: 'bg-slate-900',
    badgeText: 'text-white',
    userCount: 1,
    isSystem: true,
    defaultPermissions: ['*'],
  },
  {
    id: 'SUPER_ADMIN',
    label: 'Administrateur Général',
    category: 'DIRECTION',
    description: 'Gestion globale des opérations, support, affectations et supervision des équipes sans autorisations financières critiques.',
    color: '#3b82f6',
    badgeBg: 'bg-blue-600',
    badgeText: 'text-white',
    userCount: 2,
    isSystem: true,
    defaultPermissions: [
      'orders.view', 'orders.create', 'orders.edit', 'orders.cancel', 'orders.assign',
      'deliveries.view', 'deliveries.assign', 'drivers.view', 'drivers.manage',
      'closers.view', 'closers.manage', 'merchants.view', 'merchants.manage',
      'conversations.view', 'conversations.reply', 'conversations.escalate',
      'notifications.view', 'notifications.manage', 'users.view', 'users.create',
      'users.edit', 'users.suspend', 'settings.view', 'audit.view'
    ],
  },
  {
    id: 'TREASURY_MANAGER',
    label: 'Responsable de Trésorerie',
    category: 'FINANCE',
    description: 'Contrôle des caisses COD, validation des remises livreurs, gestion des commissions et vérification des retraits.',
    color: '#059669',
    badgeBg: 'bg-emerald-600',
    badgeText: 'text-white',
    userCount: 3,
    isSystem: true,
    defaultPermissions: [
      'orders.view', 'deliveries.view', 'drivers.view', 'merchants.view',
      'conversations.view', 'conversations.reply', 'finance.view', 'finance.manage',
      'commissions.view', 'withdrawals.view', 'withdrawals.validate',
      'notifications.view', 'audit.view'
    ],
  },
  {
    id: 'LOGISTICS_MANAGER',
    label: 'Responsable Logistique',
    category: 'OPERATIONS',
    description: 'Supervision des tournées de livraison, flotte de coursiers, retours, litiges et stocks agence.',
    color: '#d97706',
    badgeBg: 'bg-amber-600',
    badgeText: 'text-white',
    userCount: 2,
    isSystem: true,
    defaultPermissions: [
      'orders.view', 'orders.edit', 'orders.assign', 'deliveries.view', 'deliveries.assign',
      'drivers.view', 'drivers.manage', 'conversations.view', 'conversations.reply',
      'notifications.view'
    ],
  },
  {
    id: 'CLOSEUSE',
    label: 'Closeuse / Télévendeuse',
    category: 'OPERATIONS',
    description: 'Qualification téléphonique des commandes, confirmation des paniers et support client direct.',
    color: '#8b5cf6',
    badgeBg: 'bg-purple-600',
    badgeText: 'text-white',
    userCount: 3,
    isSystem: true,
    defaultPermissions: [
      'orders.view', 'orders.edit', 'conversations.view', 'conversations.reply',
      'notifications.view'
    ],
  },
  {
    id: 'LIVREUR',
    label: 'Livreur / Coursier',
    category: 'OPERATIONS',
    description: 'Prise en charge des colis, tournées terrain, encaissement COD et déclaration des remises.',
    color: '#0284c7',
    badgeBg: 'bg-sky-600',
    badgeText: 'text-white',
    userCount: 4,
    isSystem: true,
    defaultPermissions: [
      'deliveries.view', 'notifications.view'
    ],
  },
  {
    id: 'PARTNER',
    label: 'E-commerçant / Marchand',
    category: 'PARTENAIRE',
    description: 'Accès portail marchand : saisie des commandes, suivi du stock, solde portefeuille et demandes de reversement.',
    color: '#475569',
    badgeBg: 'bg-slate-700',
    badgeText: 'text-white',
    userCount: 4,
    isSystem: true,
    defaultPermissions: [
      'orders.view', 'orders.create', 'conversations.view', 'conversations.reply',
      'withdrawals.view', 'notifications.view'
    ],
  },
];

// ==========================================
// 🛡️ DÉFINITION GRANULAIRE DES PERMISSIONS
// ==========================================

export const platformPermissions: PermissionDefinition[] = [
  // 1. Commandes
  { id: 'orders.view', category: 'COMMANDES', name: 'Consulter les commandes', description: 'Afficher la liste et le détail des commandes et acheteurs.' },
  { id: 'orders.create', category: 'COMMANDES', name: 'Créer des commandes', description: 'Enregistrer manuellement une commande dans le système.' },
  { id: 'orders.edit', category: 'COMMANDES', name: 'Modifier les commandes', description: 'Mettre à jour les coordonnées client, adresses et articles.' },
  { id: 'orders.cancel', category: 'COMMANDES', name: 'Annuler des commandes', description: 'Marquer une commande comme annulée avec justification.', isSensitive: true },
  { id: 'orders.assign', category: 'COMMANDES', name: 'Assigner les commandes', description: 'Attribuer une commande à une closeuse ou un livreur.' },

  // 2. Livraisons & Flotte
  { id: 'deliveries.view', category: 'LIVRAISONS', name: 'Suivre les livraisons', description: 'Consulter le tableau de bord temps réel des tournées.' },
  { id: 'deliveries.assign', category: 'LIVRAISONS', name: 'Assigner les tournées', description: 'Affecter des colis à un livreur spécifique.' },
  { id: 'drivers.view', category: 'LIVREURS', name: 'Voir la flotte livreurs', description: 'Consulter les profils et statistiques des coursiers.' },
  { id: 'drivers.manage', category: 'LIVREURS', name: 'Gérer les livreurs', description: 'Ajouter, modifier ou suspendre un compte livreur.', isSensitive: true },

  // 3. Pôle Télévente & Marchands
  { id: 'closers.view', category: 'CLOSEUSES', name: 'Voir le pôle closeuses', description: 'Consulter les performances et disponibilités de télévente.' },
  { id: 'closers.manage', category: 'CLOSEUSES', name: 'Gérer les closeuses', description: 'Ajouter ou configurer les capacités des closeuses.', isSensitive: true },
  { id: 'merchants.view', category: 'ECOMMERCE', name: 'Voir les e-commerçants', description: 'Consulter la liste des boutiques et marchands inscrits.' },
  { id: 'merchants.manage', category: 'ECOMMERCE', name: 'Gérer les e-commerçants', description: 'Valider, modifier les commissions ou suspendre une boutique.', isSensitive: true },

  // 4. Communication & Support
  { id: 'conversations.view', category: 'CONVERSATIONS', name: 'Lire les conversations', description: 'Accéder aux discussions marchands, closeuses et livreurs.' },
  { id: 'conversations.reply', category: 'CONVERSATIONS', name: 'Répondre aux messages', description: 'Envoyer des messages et pièces jointes.' },
  { id: 'conversations.escalate', category: 'CONVERSATIONS', name: 'Escalader les échanges', description: 'Transférer ou solliciter l\'arbitrage de la direction.' },

  // 5. Finances & Trésorerie
  { id: 'finance.view', category: 'FINANCES', name: 'Consulter la trésorerie', description: 'Accéder aux flux financiers, soldes et caisses COD.' },
  { id: 'finance.manage', category: 'FINANCES', name: 'Gérer la trésorerie', description: 'Valider les remises d\'espèces et ajustements de caisse.', isSensitive: true },
  { id: 'commissions.view', category: 'FINANCES', name: 'Voir les commissions', description: 'Consulter les marges et commissions acquises par ENO.' },
  { id: 'withdrawals.view', category: 'FINANCES', name: 'Consulter les retraits', description: 'Voir les demandes de virement des partenaires.' },
  { id: 'withdrawals.validate', category: 'FINANCES', name: 'Valider les retraits', description: 'Approuver ou rejeter les demandes de reversement.', isSensitive: true },
  { id: 'withdrawals.pay', category: 'FINANCES', name: 'Décaisser les retraits', description: 'Exécuter le paiement réel via Mobile Money, Binance ou USDT.', isSensitive: true },

  // 6. Système, Administration & Sécurité
  { id: 'notifications.view', category: 'NOTIFICATIONS', name: 'Voir les notifications', description: 'Consulter les alertes et signaux opérationnels.' },
  { id: 'notifications.manage', category: 'NOTIFICATIONS', name: 'Gérer les alertes', description: 'Configurer les canaux et règles de notification.' },
  { id: 'users.view', category: 'UTILISATEURS', name: 'Voir les utilisateurs', description: 'Consulter l\'annuaire des comptes de la plateforme.' },
  { id: 'users.create', category: 'UTILISATEURS', name: 'Créer des utilisateurs', description: 'Ajouter un collaborateur ou un compte marchand.', isSensitive: true },
  { id: 'users.edit', category: 'UTILISATEURS', name: 'Modifier les utilisateurs', description: 'Mettre à jour les coordonnées et affectations.', isSensitive: true },
  { id: 'users.suspend', category: 'UTILISATEURS', name: 'Suspendre des comptes', description: 'Bloquer temporairement ou réactiver un utilisateur.', isSensitive: true },
  { id: 'roles.manage', category: 'PARAMETRES', name: 'Gérer les permissions', description: 'Modifier la matrice de droits par rôle.', isSensitive: true },
  { id: 'settings.manage', category: 'PARAMETRES', name: 'Modifier la configuration', description: 'Mettre à jour les règles opérationnelles et financières.', isSensitive: true },
  { id: 'audit.view', category: 'AUDIT', name: 'Consulter l\'audit log', description: 'Examiner le journal central des actions et sessions de sécurité.', isSensitive: true },
];

export const initialRolePermissionsMap: Record<string, string[]> = {
  PDG: platformPermissions.map((p) => p.id),
  SUPER_ADMIN: [
    'orders.view', 'orders.create', 'orders.edit', 'orders.cancel', 'orders.assign',
    'deliveries.view', 'deliveries.assign', 'drivers.view', 'drivers.manage',
    'closers.view', 'closers.manage', 'merchants.view', 'merchants.manage',
    'conversations.view', 'conversations.reply', 'conversations.escalate',
    'notifications.view', 'notifications.manage', 'users.view', 'users.create',
    'users.edit', 'users.suspend', 'settings.manage', 'audit.view'
  ],
  TREASURY_MANAGER: [
    'orders.view', 'deliveries.view', 'drivers.view', 'merchants.view',
    'conversations.view', 'conversations.reply', 'finance.view', 'finance.manage',
    'commissions.view', 'withdrawals.view', 'withdrawals.validate',
    'notifications.view', 'audit.view'
  ],
  LOGISTICS_MANAGER: [
    'orders.view', 'orders.edit', 'orders.assign', 'deliveries.view', 'deliveries.assign',
    'drivers.view', 'drivers.manage', 'conversations.view', 'conversations.reply',
    'notifications.view'
  ],
  CLOSEUSE: [
    'orders.view', 'orders.edit', 'conversations.view', 'conversations.reply',
    'notifications.view'
  ],
  LIVREUR: [
    'deliveries.view', 'notifications.view'
  ],
  PARTNER: [
    'orders.view', 'orders.create', 'conversations.view', 'conversations.reply',
    'withdrawals.view', 'notifications.view'
  ],
};

// ==========================================
// 👥 ANNUAIRE INITIAL DES UTILISATEURS
// ==========================================

export const initialPlatformUsers: PlatformUser[] = [
  {
    id: 'usr-pdg',
    firstName: 'Jude',
    lastName: 'Sinaberogui',
    name: 'Jude Sinaberogui',
    email: 'jude@enolivraison.com',
    phone: '+229 01 64 29 18 84',
    role: 'PDG',
    roleLabel: 'Président Directeur Général',
    status: 'active',
    avatarUrl: '/avatars/jude.jpg',
    createdAt: '2026-01-01',
    lastLoginAt: 'Aujourd\'hui à 11:42',
    lastActiveAt: 'En ligne',
    zone: 'Siège Cotonou',
    is2FAEnabled: true,
    twoFactorMethod: 'AUTHENTICATOR',
    notes: 'Compte souverain fondateur ENO.',
  },
  {
    id: 'usr-admin-1',
    firstName: 'Marc',
    lastName: 'Kouassi',
    name: 'Marc Kouassi',
    email: 'marc.kouassi@enolivraison.com',
    phone: '+229 01 93 83 79 06',
    role: 'SUPER_ADMIN',
    roleLabel: 'Administrateur Général',
    status: 'active',
    createdAt: '2026-01-15',
    lastLoginAt: 'Aujourd\'hui à 09:15',
    lastActiveAt: 'Il y a 12 min',
    zone: 'Agence Cotonou',
    is2FAEnabled: true,
    twoFactorMethod: 'SMS',
  },
  {
    id: 'usr-tresor-1',
    firstName: 'Amina',
    lastName: 'Tidjani',
    name: 'Amina Tidjani',
    email: 'amina.tidjani@enolivraison.com',
    phone: '+229 01 65 44 22 11',
    role: 'TREASURY_MANAGER',
    roleLabel: 'Responsable de Trésorerie',
    status: 'active',
    createdAt: '2026-02-01',
    lastLoginAt: 'Aujourd\'hui à 10:30',
    lastActiveAt: 'Il y a 25 min',
    zone: 'Caisse Centrale Cotonou',
    is2FAEnabled: true,
    twoFactorMethod: 'AUTHENTICATOR',
  },
  {
    id: 'usr-logist-1',
    firstName: 'Moussa',
    lastName: 'Dossou',
    name: 'Moussa Dossou',
    email: 'moussa.dossou@enolivraison.com',
    phone: '+229 01 67 51 00 82',
    role: 'LOGISTICS_MANAGER',
    roleLabel: 'Responsable Logistique',
    status: 'active',
    createdAt: '2026-02-10',
    lastLoginAt: 'Aujourd\'hui à 08:00',
    lastActiveAt: 'Il y a 40 min',
    zone: 'Hub Lokossa',
    is2FAEnabled: false,
  },
  {
    id: 'usr-closer-1',
    firstName: 'Sarah',
    lastName: 'Kone',
    name: 'Sarah Kone',
    email: 'sarah.kone@enolivraison.com',
    phone: '+229 01 92 33 44 55',
    role: 'CLOSEUSE',
    roleLabel: 'Closeuse Télévente',
    status: 'active',
    createdAt: '2026-02-15',
    lastLoginAt: 'Aujourd\'hui à 08:45',
    lastActiveAt: 'En ligne',
    zone: 'Pôle Télévente Cotonou',
    is2FAEnabled: false,
  },
  {
    id: 'usr-closer-2',
    firstName: 'Marie',
    lastName: 'Dossou',
    name: 'Marie Dossou',
    email: 'marie.dossou@enolivraison.com',
    phone: '+229 01 93 44 55 66',
    role: 'CLOSEUSE',
    roleLabel: 'Closeuse Télévente',
    status: 'active',
    createdAt: '2026-02-20',
    lastLoginAt: 'Aujourd\'hui à 09:00',
    lastActiveAt: 'Il y a 5 min',
    zone: 'Pôle Télévente Cotonou',
    is2FAEnabled: false,
  },
  {
    id: 'usr-driver-1',
    firstName: 'Paul',
    lastName: 'Agossou',
    name: 'Paul Agossou',
    email: 'paul.agossou@enolivraison.com',
    phone: '+229 01 95 12 34 56',
    role: 'LIVREUR',
    roleLabel: 'Livreur Moto',
    status: 'active',
    createdAt: '2026-03-01',
    lastLoginAt: 'Aujourd\'hui à 07:30',
    lastActiveAt: 'En tournée',
    zone: 'Zone 1 — Cadjehoun / Haie Vive',
    is2FAEnabled: false,
  },
  {
    id: 'usr-driver-2',
    firstName: 'Koffi',
    lastName: 'Mensah',
    name: 'Koffi Mensah',
    email: 'koffi.mensah@enolivraison.com',
    phone: '+229 01 96 23 45 67',
    role: 'LIVREUR',
    roleLabel: 'Livreur Moto',
    status: 'suspended',
    createdAt: '2026-03-05',
    lastLoginAt: 'Hier à 17:00',
    lastActiveAt: 'Inactif',
    zone: 'Zone 2 — Akpakpa / PK3',
    is2FAEnabled: false,
    notes: 'Compte suspendu pour audit d\'écart de versement COD.',
  },
  {
    id: 'usr-partner-1',
    firstName: 'Jude',
    lastName: 'Sinaberogui',
    name: 'Afrimarket SARL',
    email: 'contact@afrimarket.bj',
    phone: '+229 01 64 29 18 84',
    role: 'PARTNER',
    roleLabel: 'E-commerçant Partenaire',
    status: 'active',
    createdAt: '2026-01-15',
    lastLoginAt: 'Aujourd\'hui à 11:30',
    lastActiveAt: 'Il y a 10 min',
    zone: 'Cotonou',
    is2FAEnabled: true,
  },
];

// ==========================================
// ⚙️ CONFIGURATION GLOBALE INITIALE
// ==========================================

export const initialPlatformSettings: PlatformSettings = {
  general: {
    platformName: 'ENO LIVRAISON',
    companyName: 'ENO LOGISTICS TECH SARL',
    logoUrl: '/images/eno_livraison_logo.png',
    supportEmail: 'contact@enolivraison.com',
    supportPhone: '+229 01 64 29 18 84',
    secondaryPhone: '+229 01 93 83 79 06',
    whatsappContact: '+229 01 64 29 18 84',
    headquartersAddress: 'Cadjehoun / Haie Vive, Rue 340, Cotonou, Bénin',
    currency: 'FCFA',
    timezone: 'Africa/Porto-Novo (GMT+1)',
    dateFormat: 'DD/MM/YYYY',
    maintenanceMode: false,
    allowPublicRegistration: true,
  },
  operational: {
    ordersAssignmentMode: 'SMART_AUTO',
    conversationsAssignmentMode: 'SMART_AUTO',
    maxCapacityPerCloser: 15,
    maxCapacityPerDriver: 20,
    estimatedDeliveryMinutes: 120,
    criticalDelayHours: 4,
    autoRedistribute: true,
    redistributeTimeoutMinutes: 30,
    operatingHoursStart: '08:00',
    operatingHoursEnd: '20:30',
    sundayDeliveries: false,
    requireDeliveryPhotoConfirmation: true,
    enableCodSecurityLimits: true,
    maxDriverCodCeilingFCFA: 150000,
  },
  financial: {
    defaultClosingFee: 800,
    defaultDeliveryFee: 2000,
    defaultCommissionRate: 5,
    minWithdrawalThreshold: 10000,
    maxDailyWithdrawalLimit: 5000000,
    payoutProcessingDelayHours: 24,
    autoApprovePayoutsBelow: 50000,
    requireDoubleValidationAbove: 500000,
    codReconciliationDeadlineHours: 24,
  },
  paymentGateways: {
    leekpay: {
      enabled: true,
      environment: 'PRODUCTION',
      status: 'ACTIVE',
      webhookConfigured: true,
      supportedChannels: ['MTN Mobile Money', 'Moov Money Bénin', 'Orange Money CI', 'Wave Côte d\'Ivoire'],
      publicKeyMasked: 'pk_live_••••••••••••••••94f2',
      apiEndpoint: 'https://api.leekpay.com/v1',
    },
    binancePay: {
      enabled: true,
      status: 'ACTIVE',
      merchantIdMasked: 'BNP_••••••••2841',
      webhookConfigured: true,
      supportedCurrencies: ['USDT', 'BUSD', 'BNB'],
    },
    usdtCrypto: {
      enabled: true,
      status: 'ACTIVE',
      supportedNetworks: ['TRC-20 (Tron)', 'BEP-20 (BNB Smart Chain)', 'ERC-20 (Ethereum)', 'Polygon'],
      defaultNetwork: 'TRC-20 (Tron)',
      walletAddressMasked: 'TXk7••••••••••••••••••••••••••3z8K',
      minWithdrawalUsdt: 20,
    },
  },
  notifications: {
    orders: {
      newOrder: true,
      unassignedOrder: true,
      cancelledOrder: true,
      orderDelivered: true,
    },
    deliveries: {
      delayedDelivery: true,
      failedDelivery: true,
      criticalDelay: true,
    },
    finances: {
      newPayoutRequest: true,
      codDiscrepancy: true,
      highValueRemittance: true,
      withdrawalPaid: true,
    },
    system: {
      criticalIncident: true,
      securityAlert: true,
      dailyBackupSummary: true,
      userSuspension: true,
    },
  },
  security: {
    enforce2FAForAdmins: true,
    sessionTimeoutMinutes: 120,
    maxFailedLoginAttempts: 5,
    lockoutDurationMinutes: 30,
    requirePasswordChangeDays: 90,
    ipWhitelistEnabled: false,
    allowedIps: ['41.85.160.22', '197.234.221.10'],
    auditAllAdminActions: true,
  },
  lastUpdated: '04 sept. 2026 à 11:30',
  updatedBy: 'Jude S. (PDG)',
};
